CREATE DATABASE testing;
USE testing;
CREATE TABLE user(
id INT PRIMARY KEY AUTO_INCREMENT,
FName VARCHAR(25) NOT NULL,
LName VARCHAR(25) NOT NULL,
email_address VARCHAR(25) UNIQUE NOT NULL,
Phone_Number VARCHAR(25) UNIQUE NOT NULL
);